[package]
name = "rust-raytracer"
version = "0.1.0"
authors = ["Aaron Curtis <hippopotamus.prime@cadae.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
